version: '3.3'

services:
  web:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    links:
      - mysql
    environment:
      - DB_PORT=3306
      - DB_HOST=mysql
      - DB_NAME=test
      - DB_PASS=password
      - DB_USER=root
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./mysql:/var/lib/mysql